### PR TITLE
feat: fssdeployment script

### PR DESCRIPTION
**Pull request by JustinDPerkins**
## Cloud One Service
**select one or multiple if applicable**

[X ] **File Storage Security**

## Proposed Changes
  - a python script to deploy FSS storage stacks to existing s3 buckets.

### CODE REVIEW

**Review by felipecosta09 — CHANGES_REQUESTED** [review]
That is an awesome project ❤️!

Everything is looking good to me, only comment is to change the path, instead of  ```deploy-to-all-existing-s3``` you should use ```python-deploy-to-all-existing-s3```

**Comment by JustinDPerkins** [comment]
Done, also added that change in the readme links.

**Review by felipecosta09 — APPROVED** [review]

**Comment by felipecosta09** [comment]
> Done, also added that change in the readme links.

Awesome! LGTM

**Comment by GeorgeDavis-TM** [comment]
@JustinDPerkins It would be best to also follow the FSS plugins naming convention system "platform"-"language"-"project-name" so we can differentiate AWS, Azure and GCP.

**Pull request merged**
